admin-service
├── src
│   ├── app.js
│   ├── config
│   │   └── database.js
│   ├── controllers
│   │   └── admin.controller.js
│   ├── models
│   │   └── Admin.js
│   └── routes
│       └── admin.route.js
├── Dockerfile
├── package.json
└── README.md